# Class 3 :Pivoto tables

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
%ls datasets/

adult.csv                  census.csv     movies.csv
airline_data.csv           coches.csv     nhanes_2015_2016.csv
antropometria00.csv        cwurData.csv   pokemon.csv
antropometria-dataset.csv  data.csv       reg_data.csv
Book3.csv                  headbrain.csv  sample_pivot.csv
Canada.xlsx                mic2.xlsx      tips.csv
Cartwheeldata.csv          mic.xlsx       weight-height.csv

In [4]:
df = pd.read_csv ('datasets/census.csv')
df.head(2)

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333

In [5]:
x = df.columns.tolist()
x.sort()
x

['BIRTHS2010',
 'BIRTHS2011',
 'BIRTHS2012',
 'BIRTHS2013',
 'BIRTHS2014',
 'BIRTHS2015',
 'CENSUS2010POP',
 'COUNTY',
 'CTYNAME',
 'DEATHS2010',
 'DEATHS2011',
 'DEATHS2012',
 'DEATHS2013',
 'DEATHS2014',
 'DEATHS2015',
 'DIVISION',
 'DOMESTICMIG2010',
 'DOMESTICMIG2011',
 'DOMESTICMIG2012',
 'DOMESTICMIG2013',
 'DOMESTICMIG2014',
 'DOMESTICMIG2015',
 'ESTIMATESBASE2010',
 'GQESTIMATES2010',
 'GQESTIMATES2011',
 'GQESTIMATES2012',
 'GQESTIMATES2013',
 'GQESTIMATES2014',
 'GQESTIMATES2015',
 'GQESTIMATESBASE2010',
 'INTERNATIONALMIG2010',
 'INTERNATIONALMIG2011',
 'INTERNATIONALMIG2012',
 'INTERNATIONALMIG2013',
 'INTERNATIONALMIG2014',
 'INTERNATIONALMIG2015',
 'NATURALINC2010',
 'NATURALINC2011',
 'NATURALINC2012',
 'NATURALINC2013',
 'NATURALINC2014',
 'NATURALINC2015',
 'NETMIG2010',
 'NETMIG2011',
 'NETMIG2012',
 'NETMIG2013',
 'NETMIG2014',
 'NETMIG2015',
 'NPOPCHG_2010',
 'NPOPCHG_2011',
 'NPOPCHG_2012',
 'NPOPCHG_2013',
 'NPOPCHG_2014',
 'NPOPCHG_2015',
 'POPESTIMATE2010',
 'POPESTIMATE2011',
 'POPESTIMATE2012',
 'POPESTIMATE2013',
 'POPESTIMATE2014',
 'POPESTIMATE2015',
 'RBIRTH2011',
 'RBIRTH2012',
 'RBIRTH2013',
 'RBIRTH2014',
 'RBIRTH2015',
 'RDEATH2011',
 'RDEATH2012',
 'RDEATH2013',
 'RDEATH2014',
 'RDEATH2015',
 'RDOMESTICMIG2011',
 'RDOMESTICMIG2012',
 'RDOMESTICMIG2013',
 'RDOMESTICMIG2014',
 'RDOMESTICMIG2015',
 'REGION',
 'RESIDUAL2010',
 'RESIDUAL2011',
 'RESIDUAL2012',
 'RESIDUAL2013',
 'RESIDUAL2014',
 'RESIDUAL2015',
 'RINTERNATIONALMIG2011',
 'RINTERNATIONALMIG2012',
 'RINTERNATIONALMIG2013',
 'RINTERNATIONALMIG2014',
 'RINTERNATIONALMIG2015',
 'RNATURALINC2011',
 'RNATURALINC2012',
 'RNATURALINC2013',
 'RNATURALINC2014',
 'RNATURALINC2015',
 'RNETMIG2011',
 'RNETMIG2012',
 'RNETMIG2013',
 'RNETMIG2014',
 'RNETMIG2015',
 'STATE',
 'STNAME',
 'SUMLEV']

In [6]:
myPivot = pd.pivot_table(df,
                         index = ['STNAME','CTYNAME'],
                         values = ['BIRTHS2010','BIRTHS2011'],
                         aggfunc = ['sum','median','count'],
                         columns = 'REGION',
                         margins = True
                        )
myPivot

                               sum                                         \
                        BIRTHS2010
REGION                           1         2         3         4      All
STNAME  CTYNAME
Alabama Alabama                NaN       NaN   14226.0       NaN    14226
        Autauga County         NaN       NaN     151.0       NaN      151
        Baldwin County         NaN       NaN     517.0       NaN      517
        Barbour County         NaN       NaN      70.0       NaN       70
        Bibb County            NaN       NaN      44.0       NaN       44
...                            ...       ...       ...       ...      ...
Wyoming Uinta County           NaN       NaN       NaN      73.0       73
        Washakie County        NaN       NaN       NaN      26.0       26
        Weston County          NaN       NaN       NaN      26.0       26
        Wyoming                NaN       NaN       NaN    1995.0     1995
All                       326842.0  425250.0  737504.0  486076.0  1975672

                                                                              \
                        BIRTHS2011
REGION                           1          2          3          4      All
STNAME  CTYNAME
Alabama Alabama                NaN        NaN    59689.0        NaN    59689
        Autauga County         NaN        NaN      636.0        NaN      636
        Baldwin County         NaN        NaN     2187.0        NaN     2187
        Barbour County         NaN        NaN      335.0        NaN      335
        Bibb County            NaN        NaN      266.0        NaN      266
...                            ...        ...        ...        ...      ...
Wyoming Uinta County           NaN        NaN        NaN      324.0      324
        Washakie County        NaN        NaN        NaN      108.0      108
        Weston County          NaN        NaN        NaN       81.0       81
        Wyoming                NaN        NaN        NaN     7471.0     7471
All                      1292520.0  1669786.0  3019186.0  1965478.0  7946970

                         ...      count                               \
                         ... BIRTHS2010
REGION                   ...          1       2       3      4   All
STNAME  CTYNAME          ...
Alabama Alabama          ...        NaN     NaN     1.0    NaN     1
        Autauga County   ...        NaN     NaN     1.0    NaN     1
        Baldwin County   ...        NaN     NaN     1.0    NaN     1
        Barbour County   ...        NaN     NaN     1.0    NaN     1
        Bibb County      ...        NaN     NaN     1.0    NaN     1
...                      ...        ...     ...     ...    ...   ...
Wyoming Uinta County     ...        NaN     NaN     NaN    1.0     1
        Washakie County  ...        NaN     NaN     NaN    1.0     1
        Weston County    ...        NaN     NaN     NaN    1.0     1
        Wyoming          ...        NaN     NaN     NaN    1.0     1
All                      ...      226.0  1067.0  1439.0  461.0  3193


                        BIRTHS2011
REGION                           1       2       3      4   All
STNAME  CTYNAME
Alabama Alabama                NaN     NaN     1.0    NaN     1
        Autauga County         NaN     NaN     1.0    NaN     1
        Baldwin County         NaN     NaN     1.0    NaN     1
        Barbour County         NaN     NaN     1.0    NaN     1
        Bibb County            NaN     NaN     1.0    NaN     1
...                            ...     ...     ...    ...   ...
Wyoming Uinta County           NaN     NaN     NaN    1.0     1
        Washakie County        NaN     NaN     NaN    1.0     1
        Weston County          NaN     NaN     NaN    1.0     1
        Wyoming                NaN     NaN     NaN    1.0     1
All                          226.0  1067.0  1439.0  461.0  3193

[3193 rows x 30 columns]

In [7]:
%ls datasets

adult.csv                  census.csv     movies.csv
airline_data.csv           coches.csv     nhanes_2015_2016.csv
antropometria00.csv        cwurData.csv   pokemon.csv
antropometria-dataset.csv  data.csv       reg_data.csv
Book3.csv                  headbrain.csv  sample_pivot.csv
Canada.xlsx                mic2.xlsx      tips.csv
Cartwheeldata.csv          mic.xlsx       weight-height.csv

In [9]:
pd.read_csv('datasets/airline_data.csv', low_memory=False)
df.head(2)

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333

In [ ]:
%ls datasets/

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('datasets/airline_data.csv')
df.head(2)